apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-volume1
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"