apiVersion: v1
kind: Secret
metadata:
    name: dev-secrets
type: Opaque
data:
    mysql-password: dmV0cmk= #vetri
    postgres-user: dmV0cmk= #vetri    
    postgres-password: dmV0cmk= #vetri  
    mongodb-user: dmV0cmk= #vetri    
    mongodb-password: dmV0cmk= #vetri      